name: Deploy master
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.citydogs.gr
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}          
          server-dir: httpdocs
          dry-run: true
